getUser:
  handler: src/function/user/get/index.handler
  package:
    include:
      - "!**/*"
      - src/function/user/get/**
  events:
    - schedule:
        rate: rate(5 minutes)
        enabled: ${strToBool(${self:custom.scheduleEnabled.${env:STAGE_NAME}})}
        input:
          warmer: true
    - http:
        path: /user
        method: 'GET'
        cors: true
        caching:
          enabled: false
          cacheKeyParameters:
            #- name: request.header.Authorization
            #- name: request.header.x-api-key
        documentation:
          summary: "/user"
          description: "Get a list of user"
          methodResponses:
            - statusCode: 200
              responseBody:
                description: "A successful response"
              responseModels:
                application/json: "UserListResponse"
            - statusCode: 500
              responseBody:
                description: "Internal Server Error"
              responseModels:
                application/json: "ErrorResponse"
            - statusCode: 400
              responseBody:
                description: "Request error"
              responseModels:
                application/json: "BadRequestResponse"
