deleteUserById:
  handler: src/function/user/_id/delete/index.handler
  package:
    include:
      - "!**/*"
      - src/function/user/_id/delete/**
  events:
    - schedule:
        rate: rate(5 minutes)
        enabled: ${strToBool(${self:custom.scheduleEnabled.${env:STAGE_NAME}})}
        input:
          warmer: true
    - http:
        path: /user/{id}
        method: 'DELETE'
        cors: true
        documentation:
          summary: "/user/{id}"
          description: "Delete a specific user"
          pathParams:
            - name: id
              description: "User identifier"
              in: path
              schema:
                type: "integer"
          methodResponses:
            - statusCode: 200
              responseBody:
                description: "A successful response"
              responseModels:
                application/json: "UserResponse"
            - statusCode: 500
              responseBody:
                description: "Internal Server Error"
              responseModels:
                application/json: "ErrorResponse"
            - statusCode: 400
              responseBody:
                description: "Request error"
              responseModels:
                application/json: "BadRequestResponse"
