version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      # Update packages
      - apt update -y
      # Install yarn
      - npm install -g corepack
      - corepack enable
      # Install dependencies
      - yarn install
      # Install osls come dipendenza locale
      - yarn add osls
      # Install redocly come dipendenza locale
      - yarn add @redocly/cli
      # Install project dependencies
      - yarn layer-dependencies-install && yarn layer-shared-install
      # Configure serverless cli user
      - npx osls config credentials --provider aws --key $AWS_KEY --secret $AWS_SECRET
  build:
    commands:
      # Generate documentation
      - npx osls openapi generate -o ./doc/openapi.yaml -a 3.0.3 -f yaml
      - npx osls openapi generate -o ./doc/openapi.json -a 3.0.3 -f json -p ./doc/postman.json
      - npx redocly lint ./doc/openapi.yaml --generate-ignore-file
      - npx redocly build-docs ./doc/openapi.yaml --output=./doc/index.html
      # Move generated documentation to s3
      - AWS_ACCESS_KEY_ID=$AWS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET aws s3 cp ./doc/index.html s3://$DOC_BUCKET/$STAGE_NAME/index.html
      - AWS_ACCESS_KEY_ID=$AWS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET aws s3 cp ./doc/postman.json s3://$DOC_BUCKET/$STAGE_NAME/postman.json
      - AWS_ACCESS_KEY_ID=$AWS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET aws s3 cp ./doc/openapi.json s3://$DOC_BUCKET/$STAGE_NAME/openapi.json
      - AWS_ACCESS_KEY_ID=$AWS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET aws s3 cp ./doc/openapi.yaml s3://$DOC_BUCKET/$STAGE_NAME/openapi.yaml
      # Execute test with jest
      # yarn test
      # Deploy API with serverless
      - npx osls deploy --stage $STAGE_NAME #deploy serverless specific stage

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
