'use strict';
require('aws-sdk/lib/maintenance_mode_message').suppress = true;
const path = require('path');
// tests for postUser
// Generated by serverless-jest-plugin

const mod = require('./../../../src/function/user/post/index');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

// Import jestOpenApi plugin
const jestOpenAPI = require('jest-openapi').default;
// Load an OpenAPI file (YAML or JSON) into this plugin
let relativePath = (jasmine.testPath).split("/__tests__/")[0];
let absolutePath = path.resolve(relativePath);
jestOpenAPI(absolutePath+'/doc/build/openapi.json');

describe('postUser', () => {
  beforeAll((done) => {
    //lambdaWrapper.init(liveFunction); // Run the deployed lambda
    done();
  });

  it('Test post user', () => {

    //Define request
    let userRequest = {
      'email':'test'+Date.now()+'@eleva.it'
    };
    //Validate request
    expect(userRequest).toSatisfySchemaInApiSpec("UserRequest");

    //Create a user calling post
    return wrapped.run({
      body:userRequest
    }).then((response) => {
      //Expect response to be defined
      expect(response).toBeDefined();
      //Validate status
      expect(response.statusCode).toEqual(200);
      //Validate response against UserResponse schema
      expect(JSON.parse(response.body)).toSatisfySchemaInApiSpec("UserResponse");
    });
  });

  it('Test post user without passing email', () => {

    //Create a user calling post, passing empty body
    return wrapped.run({
      body:{}
    }).then((response) => {
      //Expect response to be defined
      expect(response).toBeDefined();
      //Validate status
      expect(response.statusCode).toEqual(400);
      //Validate response against BadRequestResponse schema
      expect(JSON.parse(response.body)).toSatisfySchemaInApiSpec("BadRequestResponse");
    });
  });

});
