getUserById:
  handler: src/function/user/_id/get/index.handler
  package:
    include:
      - "!**/*"
      - src/function/user/_id/get/**
  events:
    - schedule:
        rate: rate(5 minutes)
        enabled: ${strToBool(${self:custom.scheduleEnabled.${env:STAGE_NAME}})}
        input:
          warmer: true
    - http:
        path: /user/{id}
        method: 'GET'
        cors: true
        caching:
          enabled: false
          cacheKeyParameters:
            - name: request.path.id
            #- name: request.header.Authorization
            #- name: request.header.x-api-key
        documentation:
          summary: "/user/{id}"
          description: "Get a specific user"
          pathParams:
            - name: id
              description: "User identifier"
              in: path
              schema:
                type: "integer"
          methodResponses:
            - statusCode: 200
              responseBody:
                description: "A successful response"
              responseModels:
                application/json: "UserResponse"
            - statusCode: 500
              responseBody:
                description: "Internal Server Error"
              responseModels:
                application/json: "ErrorResponse"
            - statusCode: 400
              responseBody:
                description: "Request error"
              responseModels:
                application/json: "BadRequestResponse"
