- serverless-offline #local environment
- serverless-openapi-documenter #documentation
- serverless-slic-watch-plugin #monitoring
- serverless-api-gateway-caching #cache
- serverless-prune-plugin #reduce old version footprint
- serverless-jetpack #use jetpack as packager
