postUser:
  handler: src/function/user/post/index.handler
  package:
    include:
      - "!**/*"
      - src/function/user/post/**
  events:
    - schedule:
        rate: rate(5 minutes)
        enabled: ${strToBool(${self:custom.scheduleEnabled.${env:STAGE_NAME}})}
        input:
          warmer: true
    - http:
        path: /user
        method: 'POST'
        cors: true
        documentation:
          summary: "/user"
          description: "Create a user"
          requestBody:
            description: "A user information object"
          requestModels:
            application/json: "UserRequest"
          methodResponses:
            - statusCode: 200
              responseBody:
                description: "A successful response"
              responseModels:
                application/json: "UserResponse"
            - statusCode: 500
              responseBody:
                description: "Internal Server Error"
              responseModels:
                application/json: "ErrorResponse"
            - statusCode: 400
              responseBody:
                description: "Request error"
              responseModels:
                application/json: "BadRequestResponse"
